variables:
  CI_REGISTRY_IMAGE: 'TODO'
  PYTHON_MODULE: '{{ cookiecutter.project_slug }}'


include:
  - https://gitlab.com/GreyRook/cde/gitlab-ci-templates/raw/fc080fcacee715159427131e5cc027549366c7fc/gitlab-ci-py3.yml


